Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Reinaldo Franco Maia Damasceno
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
   Nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Nota <- 100
    escreva ("Resultado:", Nota)

Fimalgoritmo